name: bam-filter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12,<3.13
  - pip
  - scikit-build-core>=0.9
  - setuptools>=69
  - wheel
  - cython>=0.29.24
  - numpy>=1.24
  - cxx-compiler
  - pkg-config
  - htslib
  - zlib
  - igraph
  - arrow-cpp
  - duckdb
  - libduckdb-devel
  - pytest
  - pytest-cov
  - pip:
      - pytest-dependency
      - pytest-console-scripts
      - ray>=0.8.7
      - flake8
